language: node_js
node_js: stable
addons:
  firefox: latest-beta
  sauce_connect: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local -s 'default'; fi
env:
  global:
    - CXX=g++-4.8
